server:
  port: 8082

spring:
  application:
    name: item-catalog
#h2
  h2:
    console:
      enable: true
      path: /h2
# data source
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:~/item-catalog;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
    username: item
    password:
# jpa
  jpa:
    showSql: true

# eureka
eureka:
  client:
    # below 2 are not required, by default these settings are true
    registerWithEureka: true # this service will register with eureka registry server
    fetchRegistry: true      # fetch the registry information
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/
  instance:
    hostname: localhost
